INSERT into CATEGORY (description) VALUES ('American');
INSERT into CATEGORY (description) VALUES ('Italian');
INSERT into CATEGORY (description) VALUES ('Mexican');
INSERT into CATEGORY (description) VALUES ('Fast Food');
INSERT into UNIT_OF_MEASURE (uom) VALUES ('Teaspoon');
INSERT into UNIT_OF_MEASURE (uom) VALUES ('Tablespoon');
INSERT into UNIT_OF_MEASURE (uom) VALUES ('Cup');
INSERT into UNIT_OF_MEASURE (uom) VALUES ('Pinch');
INSERT into UNIT_OF_MEASURE (uom) VALUES ('Ounce');
INSERT into UNIT_OF_MEASURE (uom) VALUES ('Each');
INSERT into UNIT_OF_MEASURE (uom) VALUES ('Dash');